default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: positive_api_development

test:
  <<: *default
  database: positive_api_test

production:
  <<: *default
  database: positive_api_production
  username: positive_api
  password: <%= ENV['POSITIVE_API_DATABASE_PASSWORD'] %>
